name: BUild

on:
  workflow_dispatch:
  push:
    branches: [ dev ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3.5.3

      - name: set up JDK 17
        uses: actions/setup-java@v3.11.0
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: gradle

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2.5.1

      - name: Build with Gradle
        run: |
          ./gradlew build
